version: "3.7"
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - 3003:3003

networks:
  default:
    driver: bridge
    name: auth-service
